#!/bin/bash

set -xeuo pipefail

[[ -z ${IP:-} ]] && {
	echo "Environment variable [IP] is not defined. Cannot continue."
	exit 1
}
[[ -z ${PLAYBOOK:-} ]] && {
	echo "Environment variable [PLAYBOOK] is not defined. Cannot continue."
	exit 1
}

[[ -e ${PLAYBOOK} ]] || {
	echo "Ansible playbook defined in environment variable [PLAYBOOK] has a value of [${PLAYBOOK}]; however it doesnt exist. Cannot continue."
	exit 1
}

pkey_file=/root/.ssh/id_rsa

[[ -n ${PRIVATE_KEY_FILE:-} ]] && {
	pkey_file=${PRIVATE_KEY_FILE}
}

[[ -e ${pkey_file} ]] || {
	echo "No private ssh key has been found. By default, [/root/.ssh/id_rsa] is checked, you can override with the [PRIVATE_KEY_FILE] environment variable."
	exit 1
}

gw=$(ip r|grep -Po 'default via \S+'|awk '{print $3}')
arping ${gw} -c1
ping ${gw} -c1

cat $pkey_file

ansible --ssh-extra-args="-i ${pkey_file}" -u root -i ${IP}, -m ping

ansible-playbook --ssh-extra-args="-i ${pkey_file}" -u root -i ${IP}, ${PLAYBOOK}
