---
- hosts: all
  gather_facts: false

  roles:
    - common

  tasks:
    - name: Create a file called '/tmp/derp' with content 'derpage'.
      copy:
        content: hello world
        dest: /tmp/derp
